# .github/workflows/convert-to-pdf.yml

name: Examples to PDF
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:


jobs:
  convertviapandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet" > lorem_2.md
          mkdir pdf  # create output dir
          # this will also include README.md
          echo "::set-output name=files::$(printf '"%s" ' *.md)"
      - uses: docker://pandoc/latex:2.9
        with:
         args: --output=pdf/result.pdf
